projects:
  bopmain:
    schemaPath: graphql/schema.json
    includes:
      - 'Y'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: .
extensions:
  amplify:
    version: 3
